### ISSUE TITLE
Expiration Dates can be extended

### ISSUE THREAD

**Issue by dumain** [shiromarieke/shiro_tutorials#1]
Key expiration dates can be extended by anyone holding the private key (even after expiry).  As a consequence the security benefits are a little more subtle and require a little more work than is implied by your text.  Main benefits of expiration:
- Forces your correspondents to check for updates to the key (including revocation).
- If you keep the certification private key separate from the private subkeys it can limit the damage if subkeys are stolen.
- If you check the keyserver regularly someone else extending your expiration date may reveal that the private key have been stolen. 

Just saying that expiration limits the value of stealing your keys gives the impression that expiration is an automatic and unalterable equivalent to key revocation leading to a false sense of security.

**Comment by shiromarieke** [comment]
agreed. planned to change this as well in next version. 
version 1 has been made by some person who attended a few cryptoparties only, and we wanted to share the tutorial. the whole thing has to be updated and upgraded to be really good. it's a first idea. thanks for your comments :)
